[DEFAULT]
PRODUCT_COMPONENT=website
APP_STACK_FILE_PFIX = api_tokens_portal
APP_STACK_NAME = ala-${PRODUCT_NAME}-${ENVIRONMENT}
LAMBDA_STACK_FILE_PFIX = email_lambda
LAMBDA_STACK_NAME = ala-${PRODUCT_NAME}-lambda-${ENVIRONMENT}
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-pipeline-${ENVIRONMENT}

#app
BUCKET_PATH = www
MAX_AGE = 0
NODE_VERSION=24
VITE_APP_VERSION=0.0.1

[local]
VITE_OIDC_AUTHORITY=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_OOXU9GW39
VITE_COGNITO_LOGOUT_URI=https://auth-secure.auth.ap-southeast-2.amazoncognito.com/logout
VITE_OIDC_REDIRECT_URI=http://localhost:3000/login
VITE_OIDC_LOGOUT_REDIRECT_URI=http://localhost:3000/logout
VITE_TOKENS_API=https://api.test.ala.org.au/tokens
VITE_USERDETAILS_URL=https://auth-cognito.dev.ala.org.au/userdetails

[development]
APP_STACK_NAME = ala-${PRODUCT_NAME}-${CLEAN_BRANCH}
LAMBDA_STACK_NAME = ala-${PRODUCT_NAME}-lambda-${CLEAN_BRANCH}
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-pipeline-${CLEAN_BRANCH}
# bucket
SOURCE_BUCKET = ala-${PRODUCT_NAME}-${CLEAN_BRANCH}
MAX_AGE = 0
# cloudfront
SUB_DOMAIN = tokens-${CLEAN_BRANCH}
HOSTED_ZONE = dev.ala.org.au
DOCUMENT_ROOT = index.html
# app
VITE_OIDC_AUTHORITY=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_pQUl30qBX
VITE_COGNITO_LOGOUT_URI=https://auth-secure-development.auth.ap-southeast-2.amazoncognito.com/logout
VITE_OIDC_REDIRECT_URI=https://${SUB_DOMAIN}.${HOSTED_ZONE}/login
VITE_OIDC_LOGOUT_REDIRECT_URI=https://${SUB_DOMAIN}.${HOSTED_ZONE}/logout
VITE_TOKENS_API=https://api.test.ala.org.au/tokens
VITE_USERDETAILS_URL=https://auth-cognito.dev.ala.org.au/userdetails
# lambda
LAMBDA_CALLER=arn:aws:execute-api:ap-southeast-2:748909248546:k9w4poaf2g/*/POST/register
SOURCE_EMAIL=test@ala.org.au
DEST_EMAIL=test@ala.org.au

[testing]
# bucket
SOURCE_BUCKET = ala-${PRODUCT_NAME}-${ENVIRONMENT}
MAX_AGE = 30
# cloudfront
SUB_DOMAIN = tokens
HOSTED_ZONE = test.ala.org.au
DOCUMENT_ROOT = index.html
# app
VITE_OIDC_AUTHORITY=https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_OOXU9GW39
VITE_COGNITO_LOGOUT_URI=https://auth-secure.auth.ap-southeast-2.amazoncognito.com/logout
VITE_OIDC_REDIRECT_URI=https://${SUB_DOMAIN}.${HOSTED_ZONE}/login
VITE_OIDC_LOGOUT_REDIRECT_URI=https://${SUB_DOMAIN}.${HOSTED_ZONE}/logout
VITE_TOKENS_API=https://api.test.ala.org.au/tokens
VITE_USERDETAILS_URL=https://userdetails.test.ala.org.au
# lambda
LAMBDA_CALLER=arn:aws:execute-api:ap-southeast-2:748909248546:k9w4poaf2g/*/POST/register
SOURCE_EMAIL=test@ala.org.au
DEST_EMAIL=test@ala.org.au

[staging]
# bucket
SOURCE_BUCKET = ala-${PRODUCT_NAME}-${ENVIRONMENT}
MAX_AGE = 30
# cloudfront
SUB_DOMAIN = tokens-staging
HOSTED_ZONE = ala.org.au
DOCUMENT_ROOT = index.html
# app
VITE_OIDC_AUTHORITY=https://auth.ala.org.au/cas/oidc
VITE_COGNITO_LOGOUT_URI=https://auth-secure-auth-dev.auth.ap-southeast-2.amazoncognito.com/logout
VITE_OIDC_REDIRECT_URI=https://${SUB_DOMAIN}.${HOSTED_ZONE}/login
VITE_OIDC_LOGOUT_REDIRECT_URI=https://${SUB_DOMAIN}.${HOSTED_ZONE}/logout
VITE_TOKENS_API=https://api.ala.org.au/tokens
VITE_USERDETAILS_URL=https://auth.ala.org.au/userdetails
# lambda
LAMBDA_CALLER=arn:aws:execute-api:ap-southeast-2:736913556139:3uurj4p257/*/POST/register
SOURCE_EMAIL=info@ala.org.au
DEST_EMAIL=support@ala.org.au

[production]
# bucket
SOURCE_BUCKET = ala-${PRODUCT_NAME}-${ENVIRONMENT}
MAX_AGE = 300
# cloudfront
SUB_DOMAIN = tokens
HOSTED_ZONE = ala.org.au
SSL_CERTIFICATE = arn:aws:acm:us-east-1:736913556139:certificate/4b62cca2-9daf-4e38-b01a-48271ab3311a
DOCUMENT_ROOT = index.html
# app
VITE_OIDC_AUTHORITY=https://auth.ala.org.au/cas/oidc
VITE_COGNITO_LOGOUT_URI=https://auth-secure-auth-dev.auth.ap-southeast-2.amazoncognito.com/logout
VITE_OIDC_REDIRECT_URI=https://${SUB_DOMAIN}.${HOSTED_ZONE}/login
VITE_OIDC_LOGOUT_REDIRECT_URI=https://${SUB_DOMAIN}.${HOSTED_ZONE}/logout
VITE_TOKENS_API=https://api.ala.org.au/tokens
VITE_USERDETAILS_URL=https://auth.ala.org.au/userdetails
# lambda
LAMBDA_CALLER=arn:aws:execute-api:ap-southeast-2:736913556139:3uurj4p257/*/POST/register
SOURCE_EMAIL=info@ala.org.au
DEST_EMAIL=support@ala.org.au
